[workspace]
members = [
    "crates/dtrace-sys",
]
# Explicitly set resolver due to virtual workspace, see
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"
