[package]
name = "tick_probe"
version = "0.1.0"
edition = "2021"
description = "A simple probe that generates a tick event at constant frequency"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
color-eyre = "0.6"
composer_api = { path = "../composer_api" }
eyre = "0.6"
