[package]
name = "log_probe"
version = "0.1.0"
edition = "2021"

[dependencies]
log = {version = "0.4", features = ["std"] }
composer_api = { path = "../composer_api" }
thiserror = "1.0"

[[example]]
name = "warn_and_error_loop"
path = "examples/warn_and_error_loop.rs"