[package]
name = "composer"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
color-eyre = "0.6.2"
eyre = "0.6.8"
rodio = { version = "0.17.1", features = ["symphonia-wav"] }
serde = { version = "1.0.160", features = ["derive"] }
