[package]
name = "composer"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1"
color-eyre = "0.6"
composer_api = { path = "../composer_api" }
eyre = "0.6"
rodio = { version = "0.17", features = ["symphonia-wav"] }
