[package]
name = "ptrace_probe"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
composer = { path = "../composer" }
eyre = "0.6"
clap = { version = "*", features = ["derive"] }
fork = "0.1.21"
nix = "*"
exec = "*"
syscalls = "*"
