[package]
name = "pcap_probe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
color-eyre = "0.6"
composer_api = { path = "../composer_api" }
eyre = "0.6"
pcap = "2.2.0"
