[package]
name = "dtrace_probe"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
composer = { path = "../composer" }
dtrace = { path = "../dtrace" }
eyre = "0.6"
structopt = "0.3"
